name: 'Dreamhouse'
channels:
    - conda-forge
    - defaults
dependencies:
    - python
    - jupyterlab
    - ipykernel
    - altair-all
    - vegafusion
    - dash
    - dash-bootstrap-components
    - plotly
    - pandas
    - numpy
    - matplotlib
    - jupyter-dash
    - scikit-learn
    - pip
pip:
    - dash-vega-components